# Generated by Django 6.0.2 on 2026-02-26 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0002_initial'),
        ('stations', '0003_remove_station_ending_watt_remove_station_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charger',
            name='assigned_staff',
        ),
        migrations.CreateModel(
            name='ShiftRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('kwh_start', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kwh_end', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kwh_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_records', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_records', to='stations.station')),
            ],
            options={
                'db_table': 'shift_records',
                'ordering': ['-shift_start'],
            },
        ),
    ]
