# Generated by Django 5.2.11 on 2026-07-06 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0003_remove_charger_assigned_staff_shiftrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrecord',
            name='shift_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
