# Generated by Django 5.2.11 on 2026-07-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0005_shiftrecord_cashpower_redesign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftrecord',
            name='remaining_cashpower',
        ),
        migrations.AddField(
            model_name='shiftrecord',
            name='end_kwatts_in_cashpower',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
