# Generated by Django 5.2.11 on 2026-07-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_sessions', '0004_session_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingsession',
            name='port',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=5),
        ),
    ]
