# Generated by Django 6.0.7 on 2026-07-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_sessions', '0005_alter_chargingsession_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='is_estimated',
            field=models.BooleanField(default=False),
        ),
    ]
