# Generated by Django 6.0.7 on 2026-08-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_sessions', '0006_chargingsession_is_estimated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='amount_paid',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
