# Generated by Django 5.2.11 on 2026-07-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_phone_n_a3b1c5_idx',
            old_name='users_phone__4b85f2_idx',
        ),
    ]
