# Generated by Django 5.2.11 on 2026-07-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_users_phone__4b85f2_idx_users_phone_n_a3b1c5_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='station',
        ),
    ]
