# Generated by Django 6.0.7 on 2026-07-11 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0003_remove_station_ending_watt_remove_station_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount_vat_exclusive', models.DecimalField(decimal_places=2, max_digits=12)),
                ('input_vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='stations.station')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date'],
            },
        ),
    ]
