# Generated by Django 4.2.7 on 2026-02-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_per_watt', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('starting_watt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ending_watt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stations',
            },
        ),
    ]
