# Generated by Django 6.0.2 on 2026-02-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='ending_watt',
        ),
        migrations.RemoveField(
            model_name='station',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='station',
            name='starting_watt',
        ),
    ]
